### ISSUE TITLE
patterns.findFirstNextEmptyPat flags update

### ISSUE THREAD

**Issue by MetallicAsylum** [MiguelGuthridge/FL-Studio-API-Stubs#34]
The documentation states that FFNEP_DontPromptName is 1, where it doesn't work, but inputting 2 does work correctly and doesn't prompt a name when creating a new empty pattern.

**Comment by MiguelGuthridge** [comment]
I'll look into this as soon as I have time :)

**Comment by MiguelGuthridge** [comment]
Fixed! Will release this with the next version of the library
