### ISSUE TITLE
playlist module liveBlock update

### ISSUE THREAD

**Issue by MetallicAsylum** [MiguelGuthridge/FL-Studio-API-Stubs#35]
Hello, I noticed on the API Stubs that most Live modules have "Help Wanted" on them, and I wanted to help clarify. "Live" in FL refers to Performance Mode

getDisplayZone() gets the display zone, which is this red box that shows up in performance mode over a specific area of blocks

liveDisplayZone() sets the area for a display zone in live mode, int left starts 0, int top starts at 1 referring to Track 1, int right refers to the amount of bars right, and int bottom refers to the bottom Track number.

getLiveLoopMode() at the int Track index gets the selection in the "Motion" tab when right clicking a track and looking at "Performance Settings"

getLiveTriggerMode() at the int Track index gets the selection in the "Press" tab when right clicking a track and looking at "Performance Settings"

getLivePosSnap() at the int Track index gets the selection in the "Position Sync" tab when right clicking a track and looking at "Performance Settings"

getLiveTrigSnap() at the int Track index gets the selection in the "Trigger Sync" tab when right clicking a track and looking at "Performance Settings"

getLiveStatus() at the int Track index gets if at the track index if any blocks are playing, scheduled, or if its empty

getLiveBlockStatus() at Track index, block index, gets back if the block is filled, scheduled, or playing (or empty with different flags)

getLiveBlockColor() at Track index, block index, gets the color of the specified block.

triggerLiveClip() at Track index, block index, flag, triggers the block clip at that index with the specified flag (I wish the documentation explained the flags)

refreshLiveClips() at Track index, for clip number refreshes the clip

incLivePosSnap, incLiveTrigSnap, incLiveLoopMode, and incLiveTrigMode at index increases the selection at "Position Sync", "Trigger Sync", "Motion", and "Press" tabs respectively for the track, I think value means what mode it uses for each one.

getVisTimeTick() I'm not sure what it gets, but I get different numbers depending on what clip I play, how many clips, and where they are in performance mode

getVisTimeStep() is a bit of the same, but I think it adds together all playing clips' positions in steps?

The ones I still couldn't figure out are lockDisplayZone() and getVisTimeBar(), but hopefully this helps you find how these work

**Comment by MetallicAsylum** [comment]
Oh also, I just noticed in the API that playlist.refreshLiveClip**s** is missing the s, do its only refreshLiveClip

**Comment by MiguelGuthridge** [comment]
Thanks for the explanations! I'll add this in as soon as I can (or if you want, you could create a pull request)

**Comment by MiguelGuthridge** [comment]
Thanks so much! I've added explanations for everything except for `lockDisplayZone` and `refreshLiveClips` (which I am still confused about). I'll check these with Image-Line myself and see what I can do.

In the mean time, the documentation should go live in the next minute or so, and I'll release a new version of the package in a couple of days, once I improve some other things.
